AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash']
